"""chat context store

迁移 ID: c254b6952d47
父迁移: 2ee162c4406c
创建时间: 2026-09-19 12:49:55.196759

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.mysql import LONGBLOB

#  MySQL / MariaDB 下 LargeBinary 会渲染成上限 64KB 的 BLOB，
#  与 max_image_kb（默认 2MB）冲突，这里与 models.ContextMedia 保持一致。
_MEDIA_BINARY_TYPE = sa.LargeBinary().with_variant(LONGBLOB(), "mysql")

revision: str = "c254b6952d47"
down_revision: str | Sequence[str] | None = "2ee162c4406c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amrita_chat_context_media",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("media_id", sa.String(length=64), nullable=False),
        sa.Column("uni_id", sa.String(length=64), nullable=False),
        sa.Column("mime", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("data", _MEDIA_BINARY_TYPE, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amrita_chat_context_media")),
        sa.UniqueConstraint("media_id", name="uq_amrita_chat_context_media_id"),
        info={"bind_key": "chat"},
    )
    with op.batch_alter_table("amrita_chat_context_media", schema=None) as batch_op:
        batch_op.create_index(
            "idx_amrita_ctx_media_created", ["created_at"], unique=False
        )
        batch_op.create_index("idx_amrita_ctx_media_uni", ["uni_id"], unique=False)

    op.create_table(
        "amrita_chat_context_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uni_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("nickname", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amrita_chat_context_record")),
        info={"bind_key": "chat"},
    )
    with op.batch_alter_table("amrita_chat_context_record", schema=None) as batch_op:
        batch_op.create_index(
            "idx_amrita_ctx_record_created", ["created_at"], unique=False
        )
        batch_op.create_index(
            "idx_amrita_ctx_record_uni_time", ["uni_id", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("amrita_chat_context_record", schema=None) as batch_op:
        batch_op.drop_index("idx_amrita_ctx_record_uni_time")
        batch_op.drop_index("idx_amrita_ctx_record_created")

    op.drop_table("amrita_chat_context_record")
    with op.batch_alter_table("amrita_chat_context_media", schema=None) as batch_op:
        batch_op.drop_index("idx_amrita_ctx_media_uni")
        batch_op.drop_index("idx_amrita_ctx_media_created")

    op.drop_table("amrita_chat_context_media")
    # ### end Alembic commands ###
